[tool.pytest.ini_options]
addopts = "-ra -q -vv"
testpaths = [
    "tests",
    "integration",
]
markers = [
    "unit: Mark for unit tests",
    "integration: Mark for integration tests",
    "high: High priority",
    "medium: Medium priority",
    "low: Low priority",
    "no_test_db: Tests that don't requires a test database",
]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.flake8]
exclude = [".venv", "build", "migrations"]
max-line-length = 101

[tool.black]
line-length = 79
target-version = ["py36", "py37"]
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | _build
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
profile = "black"
src_paths = ["dundie", "tests", "integration"]
multi_line_output = 3  # VHI
line_length = 79
force_grid_wrap = 0
use_parentheses = true
include_trailing_comma = true