[tool.pytest.ini_options]
addopts = "-ra -q -vv"
testpaths = [
    "tests",
    "integration",
]
markers = [
    "unit: Mark for unit tests",
    "integration: Mark for integration tests",
    "high: High priority",
    "medium: Medium priority",
    "low: Low priority",
]