"""Add currency colunm on person table

Revision ID: 50c6d428d9e3
Revises: 61f71d2afe24
Create Date: 2025-01-24 12:34:09.595346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "50c6d428d9e3"
down_revision: Union[str, None] = "61f71d2afe24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person",
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("person", "currency")
    # ### end Alembic commands ###
