name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

  workflow_dispatch:


jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.13']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install UV
        uses: astral-sh/setup-uv@v3

      - name: Setup Python ${{matrix.python-version}}
        run: uv python install ${{matrix.python-version}} 

      - name: Look for style errors
        run: uv run task lint

      - name: Check for importing style
        run: uvx ruff format --diff dundie tests integration

  tests:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.13']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      
      - name: Install UV
        uses: astral-sh/setup-uv@v3
      
      - name: Setup Python ${{matrix.python-version}}
        run: uv python install ${{matrix.python-version}} 
      
      - name: Run tests
        run: uv run --extra test pytest -v --forked --junitxml=test-result.xml && covarage xml
